name: Validate the mod with CK3_Validator scripts

on: [push]

jobs:
  check_localization_file_endings:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: recursive
      - name: "Clone CK3_Validator"
        run: |
          mkdir CK3_Validator
          git clone https://github.com/LT-Rascek/CK3_Validator.git CK3_Validator
      - name: "Check localization file endings"
        run: |
          find localization -name "*.txt" | xargs rm
          python3 CK3_Validator/test_scripts/check_localization_file_endings.py "."
